services:
  nginx:
    image: mon-nginx-image
    container_name: mon-nginx-image
    ports:
      - 80:80
      - 443:443
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      app-prod:
        condition: service_started
    networks:
      - shared-network

  app-prod:
    container_name: react_app_prod
    image: react-app-prod:1.0.0
    build: 
      target: production
      dockerfile: Dockerfile
    command: yarn run start:prod
    ports:
      - 3000:3000
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network: